#!/usr/bin/env python3
"""build_about_schedule.py — write the About page's schedule table from the
live Windows Task Scheduler (schtasks), not from hand-typed copy.

    python build_about_schedule.py

Writes templates/_about_schedule.html (included by templates/about.html).
Re-run it after any schtasks change. Disabled and one-time tasks are
skipped; a daily AdWriter task this script has no plain-English name for is
reported and left out, so a new task is never published under its raw name.
"""
from __future__ import annotations

import csv
import io
import subprocess
import sys
from collections import defaultdict
from datetime import date, datetime, timedelta
from html import escape
from pathlib import Path

OUT = Path(__file__).resolve().parent / "templates" / "_about_schedule.html"

# Scheduler task -> (plain-English name, what it does or "").
PLAIN = {
    "AdWriter-VisionProcess": ("Sticker image reader", ""),
    "AdWriter-Orchestrator": (
        "Morning run",
        "About 2 to 3 hours: reads inventory, checks reconditioning, writes new ads, rewrites ads when prices "
        "change, updates ads when reconditioning finishes, records click-through data, emails the results",
    ),
    "AdWriter-CTR-Email": ("Click-through email", ""),
    "AdWriter-Verifier-Hourly": ("Posting checker", ""),
    "AdWriter-ReconWarmup": ("Reconditioning check", ""),
    "AdWriter-StickerWarmup": ("Window sticker refresh", ""),
    "AdWriter-CarfaxWarmup": ("Vehicle history refresh", ""),
    "AdWriter-Browse": ("Dealer system browse", ""),
}


def _time(t: str) -> str:
    d = datetime.strptime(t.strip(), "%I:%M:%S %p")
    if d.hour == 0 and d.minute == 0:
        return "midnight"
    if d.hour == 12 and d.minute == 0:
        return "noon"
    return d.strftime("%I:%M %p").lstrip("0")


def _hours(s: str) -> int | None:
    # "2 Hour(s), 0 Minute(s)"
    try:
        h = int(s.split("Hour")[0].strip())
        m = int(s.split(",")[1].split("Minute")[0].strip())
        return h if m == 0 else None
    except (ValueError, IndexError):
        return None


def read_tasks() -> list[dict]:
    out = subprocess.run(["schtasks", "/query", "/fo", "CSV", "/v"], capture_output=True, text=True, check=True).stdout
    rows = [r for r in csv.DictReader(io.StringIO(out)) if r.get("TaskName") != "TaskName"]
    return [r for r in rows if r.get("TaskName", "").lstrip("\\").startswith("AdWriter-")]


def schedule(rows: list[dict]) -> tuple[list[tuple[str, str, str]], list[str]]:
    """([(name, when, what)], notes) in start-time order."""
    whens: dict[str, list[tuple[datetime, str]]] = defaultdict(list)
    notes = []
    for r in rows:
        task = r["TaskName"].lstrip("\\")
        if r.get("Scheduled Task State", "").strip() != "Enabled":
            notes.append(f"skipped {task}: disabled")
            continue
        if r.get("Schedule Type", "").strip() != "Daily" or r.get("Days", "").strip() != "Every 1 day(s)":
            notes.append(f"skipped {task}: {r.get('Schedule Type', '').strip()}, not daily")
            continue
        if task not in PLAIN:
            notes.append(f"LEFT OUT {task}: no plain-English name in build_about_schedule.PLAIN")
            continue
        st = r["Start Time"].strip()
        every = (r.get("Repeat: Every") or "").strip()
        if every and every != "Disabled":
            step, span = _hours(every), _hours(r.get("Repeat: Until: Duration") or "")
            t0 = datetime.strptime(st, "%I:%M:%S %p")
            end = _time((t0 + timedelta(hours=span)).strftime("%I:%M:%S %p")) if span else "end of day"
            text = f"{_time(st)} to {end}, every {step} hours" if step else f"{_time(st)}, repeating {every}"
        else:
            text = _time(st)
        whens[task].append((datetime.strptime(st, "%I:%M:%S %p"), text))
    table = []
    for t in sorted(whens, key=lambda t: min(whens[t])):
        texts = [w for _, w in sorted(set(whens[t]))]
        table.append((PLAIN[t][0], ", ".join(texts), PLAIN[t][1]))
    return table, notes


def render(table: list[tuple[str, str, str]], checked: date) -> str:
    rows = "\n".join(
        f"      <tr><td>{escape(n)}</td><td>{escape(w)}</td><td>{escape(d)}</td></tr>" for n, w, d in table
    )
    stamp = f"{checked.strftime('%B')} {checked.day}, {checked.year}"
    return (
        "{# Generated by build_about_schedule.py from schtasks. Do not edit by hand. #}\n"
        '<table class="about-schedule">\n'
        "  <thead><tr><th>Task</th><th>When (daily)</th><th>What it does</th></tr></thead>\n"
        f"  <tbody>\n{rows}\n  </tbody>\n"
        "</table>\n"
        f'<p class="about-checked">Schedule checked: {stamp}</p>\n'
    )


def main() -> int:
    table, notes = schedule(read_tasks())
    html = render(table, date.today())
    OUT.write_text(html, encoding="utf-8")
    for n, w, _ in table:
        print(f"  {n}: {w}")
    for n in notes:
        print(f"  ({n})")
    print(f"wrote {OUT}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
